* MOZ’ Lib


MOZ’Lib is a collection of bpatcher modules and objects for Max.
Its main purpose is to introduce the various problematics of computer-aided instrumental composition, programming and creation in general to young musicians between 9 and 99 years old.

MOZ’Lib is developed by composer Julien Vincenot, initially as a commission from the project Ariane#, directed by the DRAC (Regional Directorate of Cultural Affairs) of Franche-Comté region (east of France) and piloted by the Conservatory of Montbéliard.
Developed since the beginning on macOS, MOZ'Lib and the PWforMax system it contains have been ported to Windows 10 in 2021 thanks to Matteo Marson's invaluable help :) 

This new version, fully documented and translated into English, is part of his doctoral research in composition at Harvard University, under the guidance of Hans Tutschku.

Using this library requires to install Cycling’74’s Max 7 or 8 for Mac or Windows — it will work without a licence (Runtime mode) but you won’t be able to save new patches ! 
MOZ’Lib makes an extensive use of the bach library developed by Daniele Ghisi and Andrea Agostini, extended with the language SBCL (Steel Bank Common LISP), which is distributed with MOZ’Lib under GNU licence.

MOZ’Lib will remain free and open-source, just like the many pieces of CAC software it relies on. However if you enjoy this project very much and would like to buy me a beer, a pizza or a ticket for an exuberant art show or the last blockbuster movie, you can leave me a tip here : paypal.me/julienvincenot

If you want to be kept informed about future MOZ’Lib updates,
just send an email to mozlib+subscribe@googlegroups.com

-----
* Dependencies :

MOZ'Lib includes the following open-source software :
- shell object for Max by Jeremy Bernstein and Bill Orcutt
  https://github.com/jeremybernstein/shell
- SBCL (Steel Bank Common Lisp), an open source Common Lisp compiler 
  http://www.sbcl.org
  Note: MOZ'Lib contains an executable of SBCL 1.5.3 pre-compiled for macOS. New versions will be compiled when needed. In January 2020, this version is compatible with macOS Catalina.
- the moz-complete.core used for PWforMax contains a modified version of several  Lisp functions from Ircam's OpenMusic sources (based on PatchWork), as well as user libraries written for either PatchWork, OpenMusic or PWGL by Mikael Laurson and Orjan Sandred (PW Constraints aka OMCS), Jacopo Baboni Schilingi (JBS-CMI, JBS-Profile and JBS-Constraints) and Frederic Voisin (Morphologie). The core also contains the ITERATE library by Jonathan Amsterdam and Andrea Fuchs (https://common-lisp.net/project/iterate/) and a modified version of Guy Steele's backquote implementation in Common Lisp (https://www.cs.cmu.edu/Groups/AI/html/cltl/clm/node367.html)
  Note: All those are available in the sources subfolder, allowing users to recompile the core and add other libraries.

-----

* How to install MOZ'Lib :

WARNING : BEFORE INSTALLING/UPDATING, MAKE SURE YOU DON'T HAVE ANY PAST VERSION OF MOZ'LIB ON YOUR MACHINE !

1— Download and install the latest version of Max (ideally 8 but 7 works too) for Mac or PC
   https://cycling74.com/downloads/

2— Now start Max and install the last version of the bach, cage and dada libraries
   from Max’s Package Manager or bach’s official website : http://www.bachproject.net
   
   The minimum recommended version is bach 0.8.1, released in the fall 2019.
   
   If installing from the website, make sure you place the decompressed folders of bach / cage / dada into Max’s Packages folder 
   on Mac : your_user_folder/Documents/Max 8/Packages/ (or equivalent for Max 7)
   on PC : My Documents\Max8\Packages\
 




** on macOS

3— Copy the decompressed folder of MOZ’Lib in the Packages folder as well.
 
   WARNING:
   - If you downloaded the GitHub version, after unzipping you got a MOZLib-master folder.
   DO NOT place this one in packages ! Instead, unzip the MOZLib.zip inside of it, then
   place the resulting MOZLib folder in Packages.

   - If you downloaded MOZLib from my website, just unzip and place the MOZLib folder in Packages.


   IMPORTANT: 
   If your system is macOS 10.13 or later it is possible that your Documents folder 
   is actually located on iCloud Drive... PWforMax will not work in these conditions! 
   You will need either to de-activate iCloud Drive (at least for Documents and Desktop) 
   or create a dummy Documents folder in your user folder (home), with the following 
   directory structure :
             your_user_folder/Documents/Max 8/Packages/ 
             (you still put MOZLib in Packages obviously)


   VERY IMPORTANT:
   If your computer runs macOS 10.15 (Catalina) or above, MOZ'Lib will not be able to work in Max 
   unless you remove it from the system quarantine by entering the following command 
   in the terminal :
       xattr -rd com.apple.quarantine ~/Documents/Max\ 8/Packages/*
       (substitute 7 with 8 if you still use Max 7 — don't forget the * symbol !)
   This operation is mandatory to use any package not distributed on Cycling'74's Package Manager.
   
4— Restart Max and go to Extras menu -> LISP Test to check everything went well.
 




** on Windows 10


3— Copy the following Max copy compressed code inside an empty Max patch. 
This will give you the first patch needed to install MOZ'Lib properly on Windows.
Follow the procedure attentively (you'll need to restart halfway) and it will install
WSL (Windows Subsystem for Linux, Windows 10 only), install SBCL for Windows and 
download and install the MOZ files automatically.

VERY IMPORTANT: at some point in the procedure you will need to choose a username and password
for WSL. Keep those preciously, you will need them later to compile and install SBCL as well as some
other small install actions.

4— In the last install patch, don't forget to do the LISP Test included, to check everything went well.








** ...and finally

5— Go to the MOZ’Lib Intro in the Extras menu and… HAVE FUN !
